### ISSUE TITLE
Screen shots?

### ISSUE THREAD

**Issue by PySimpleGUI** [danevd-TCD/Rapid-Labelling-Tool#1]
It looks like you've got a complicated, or in the very least lengthy GUI, and I'm guessing an interesting one should I see it.  

It's easy to drop images into a project's readme.  I upload them to Issues and then use the link that's shown in the readme.md file.  It's lazy but gets images in there quickly.  Everyone likes pictures and I'm sure anyone stopping in would like to have a look.

**Comment by danevd-TCD** [comment]
Hey, thanks for checking this out! I'll add some images to the readme now, just had to get everything up yesterday for a deadline. I'm a beginner to GitHub so still getting the hang of stuff.

I just wanna give a personal thanks for all the work PySimpleGUI made possible for me; I'm a final year mechanical engineering student and went from total beginner in Python to developing a fully-functional multi-window application for my project thesis in just under 3 months, and without PySimpleGUI (and some other great packages!) I'd have gotten nowhere.

**Comment by danevd-TCD** [comment]
Images have been uploaded to readme :)

**Comment by PySimpleGUI** [comment]
OMG, WOW!
Just flipped over to your homepage and looked.  No wonder I saw so much PySimpleGUI code!  It's a massive!!  You've got a lot to be proud of.

**Comment by danevd-TCD** [comment]
> OMG, WOW!
> Just flipped over to your homepage and looked. No wonder I saw so much PySimpleGUI code! It's a massive!! You've got a lot to be proud of.

Thank you!
